/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPlaygroundRouteImport } from './routes/_layout/playground'
import { Route as LayoutModelsIndexRouteImport } from './routes/_layout/models/index'
import { Route as LayoutApikeysIndexRouteImport } from './routes/_layout/apikeys/index'
import { Route as LayoutModelsCreateRouteImport } from './routes/_layout/models/create'
import { Route as LayoutModelsIdRouteImport } from './routes/_layout/models/$id'
import { Route as LayoutApikeysCreateRouteImport } from './routes/_layout/apikeys/create'
import { Route as LayoutApikeysIdRouteImport } from './routes/_layout/apikeys/$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaygroundRoute = LayoutPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelsIndexRoute = LayoutModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApikeysIndexRoute = LayoutApikeysIndexRouteImport.update({
  id: '/apikeys/',
  path: '/apikeys/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelsCreateRoute = LayoutModelsCreateRouteImport.update({
  id: '/models/create',
  path: '/models/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelsIdRoute = LayoutModelsIdRouteImport.update({
  id: '/models/$id',
  path: '/models/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApikeysCreateRoute = LayoutApikeysCreateRouteImport.update({
  id: '/apikeys/create',
  path: '/apikeys/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApikeysIdRoute = LayoutApikeysIdRouteImport.update({
  id: '/apikeys/$id',
  path: '/apikeys/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/settings': typeof LayoutSettingsRoute
  '/apikeys/$id': typeof LayoutApikeysIdRoute
  '/apikeys/create': typeof LayoutApikeysCreateRoute
  '/models/$id': typeof LayoutModelsIdRoute
  '/models/create': typeof LayoutModelsCreateRoute
  '/apikeys/': typeof LayoutApikeysIndexRoute
  '/models/': typeof LayoutModelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/settings': typeof LayoutSettingsRoute
  '/apikeys/$id': typeof LayoutApikeysIdRoute
  '/apikeys/create': typeof LayoutApikeysCreateRoute
  '/models/$id': typeof LayoutModelsIdRoute
  '/models/create': typeof LayoutModelsCreateRoute
  '/apikeys': typeof LayoutApikeysIndexRoute
  '/models': typeof LayoutModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/playground': typeof LayoutPlaygroundRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/apikeys/$id': typeof LayoutApikeysIdRoute
  '/_layout/apikeys/create': typeof LayoutApikeysCreateRoute
  '/_layout/models/$id': typeof LayoutModelsIdRoute
  '/_layout/models/create': typeof LayoutModelsCreateRoute
  '/_layout/apikeys/': typeof LayoutApikeysIndexRoute
  '/_layout/models/': typeof LayoutModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/settings'
    | '/apikeys/$id'
    | '/apikeys/create'
    | '/models/$id'
    | '/models/create'
    | '/apikeys/'
    | '/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/settings'
    | '/apikeys/$id'
    | '/apikeys/create'
    | '/models/$id'
    | '/models/create'
    | '/apikeys'
    | '/models'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/playground'
    | '/_layout/settings'
    | '/_layout/apikeys/$id'
    | '/_layout/apikeys/create'
    | '/_layout/models/$id'
    | '/_layout/models/create'
    | '/_layout/apikeys/'
    | '/_layout/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playground': {
      id: '/_layout/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof LayoutPlaygroundRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models/': {
      id: '/_layout/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof LayoutModelsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apikeys/': {
      id: '/_layout/apikeys/'
      path: '/apikeys'
      fullPath: '/apikeys/'
      preLoaderRoute: typeof LayoutApikeysIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models/create': {
      id: '/_layout/models/create'
      path: '/models/create'
      fullPath: '/models/create'
      preLoaderRoute: typeof LayoutModelsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models/$id': {
      id: '/_layout/models/$id'
      path: '/models/$id'
      fullPath: '/models/$id'
      preLoaderRoute: typeof LayoutModelsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apikeys/create': {
      id: '/_layout/apikeys/create'
      path: '/apikeys/create'
      fullPath: '/apikeys/create'
      preLoaderRoute: typeof LayoutApikeysCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apikeys/$id': {
      id: '/_layout/apikeys/$id'
      path: '/apikeys/$id'
      fullPath: '/apikeys/$id'
      preLoaderRoute: typeof LayoutApikeysIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutPlaygroundRoute: typeof LayoutPlaygroundRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutApikeysIdRoute: typeof LayoutApikeysIdRoute
  LayoutApikeysCreateRoute: typeof LayoutApikeysCreateRoute
  LayoutModelsIdRoute: typeof LayoutModelsIdRoute
  LayoutModelsCreateRoute: typeof LayoutModelsCreateRoute
  LayoutApikeysIndexRoute: typeof LayoutApikeysIndexRoute
  LayoutModelsIndexRoute: typeof LayoutModelsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPlaygroundRoute: LayoutPlaygroundRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutApikeysIdRoute: LayoutApikeysIdRoute,
  LayoutApikeysCreateRoute: LayoutApikeysCreateRoute,
  LayoutModelsIdRoute: LayoutModelsIdRoute,
  LayoutModelsCreateRoute: LayoutModelsCreateRoute,
  LayoutApikeysIndexRoute: LayoutApikeysIndexRoute,
  LayoutModelsIndexRoute: LayoutModelsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
