//! Hand-written OpenAPI 3.1 paths + Scalar mount, with resource
//! schemas merged in from `schemas/resources/`.
//!
//! Covers every route mounted in `crate::build_router` so what you see
//! at `/admin/openapi-scalar` matches what the binary actually serves.
//! The proxy `/v1/chat/completions` surface is OpenAI-compatible and
//! operators refer to OpenAI's published spec for that — duplicating
//! it here adds drift risk without adding signal.
//!
//! Resource shapes (`Model`, `ApiKey`, `ProviderKey`, `Guardrail`,
//! `CachePolicy`, `ObservabilityExporter`, `RateLimit`, `Routing`) are
//! NOT inlined in the constant below — they live in
//! `<workspace-root>/schemas/resources/<name>.schema.json`, generated
//! from the `schemars::JsonSchema` derives on the
//! `aisix-core::models::*` types (regenerated by the `dump-schema`
//! binary; CI enforces no drift). At first call to [`openapi_json`]
//! each file is parsed, its `definitions/*` are hoisted to top-level
//! `components.schemas`, `$ref` paths are rewritten from JSON Schema's
//! `#/definitions/X` to OpenAPI's `#/components/schemas/X`, and the
//! result is cached for the process lifetime.
//!
//! The Scalar UI is a single static HTML page that loads the JSON spec
//! over HTTP — no JS bundling required.

use std::sync::OnceLock;

use axum::http::header;
use axum::response::{Html, IntoResponse, Response};
use serde_json::Value;

/// Paths + OpenAPI-specific wrapper schemas (`ModelEntry`,
/// `ApiKeyEntry`, `ModelStatusView`, `AdminError`, etc.). Resource
/// schemas live in [`RESOURCE_SCHEMAS`] below and get merged in by
/// [`merged_openapi`]. Update this whenever a route is added or
/// removed in `lib.rs`.
const OPENAPI_JSON_BASE: &str = r##"{
  "openapi": "3.1.0",
  "info": {
    "title": "AISIX Admin API",
    "version": "0.1.0",
    "description": "Admin surface for the self-hosted AISIX gateway. All `/admin/v1/*` routes require Bearer admin-key auth configured with `admin.admin_keys`. Errors use {\"error_msg\": \"...\"}.\n\nIn managed mode, the admin listener is not bound. The AISIX Cloud control plane manages configuration resources."
  },
  "paths": {
    "/livez": {
      "get": {
        "summary": "minimal public liveness probe",
        "security": [],
        "parameters": [
          {
            "name": "verbose",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "When present, returns a multi-line text report instead of the terse `ok` body."
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Liveness checks failed during shutdown",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/admin/openapi.json": {
      "get": {
        "summary": "this OpenAPI document",
        "security": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true
                }
              }
            }
          }
        }
      }
    },
    "/admin/openapi-scalar": {
      "get": {
        "summary": "Scalar UI (HTML) for browsing this spec",
        "security": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/html": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/models": {
      "get": {
        "summary": "list models",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ModelEntry"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create model",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Model"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ModelEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate display_name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/models/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "get model",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ModelEntry"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "update model",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Model"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ModelEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate display_name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete model",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/models/status": {
      "get": {
        "summary": "list per-model runtime status",
        "description": "Returns runtime routing/exclusion state for every Model. Direct models surface live runtime state keyed by resolved direct-model id; routing models return `not_applicable`. Request-path retryable failures surface as `cooldown`. Background checks can surface `unhealthy` or a healthy row with `status_reason=ignored_transient_error`.",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ModelStatusView"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/apikeys": {
      "get": {
        "summary": "list api keys",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/PublicApiKeyEntry"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create api key",
        "description": "Body carries `key_hash` (SHA-256 of plaintext). The plaintext is generated client-side; the gateway never sees it.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ApiKeyRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PublicApiKeyEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate key_hash",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/apikeys/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "get api key",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PublicApiKeyEntry"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "update api key",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ApiKeyRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PublicApiKeyEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate key_hash",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete api key",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/apikeys/{id}/rotate": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "post": {
        "summary": "rotate api key",
        "description": "Generates a new plaintext bearer, persists its SHA-256 hash, and returns the plaintext **once** under `plaintext`. Caller MUST capture — subsequent GETs only expose the hash.",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiKeyRotateResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/provider_keys": {
      "get": {
        "summary": "list provider keys",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ProviderKeyEntry"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create provider key",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProviderKey"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProviderKeyEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate display_name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/provider_keys/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "get provider key",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProviderKeyEntry"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "update provider key",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProviderKey"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProviderKeyEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate display_name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete provider key",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/guardrails": {
      "get": {
        "summary": "list guardrails",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/GuardrailEntry"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create guardrail",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Guardrail"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GuardrailEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/guardrails/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "get guardrail",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GuardrailEntry"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "update guardrail",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Guardrail"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GuardrailEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete guardrail",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/cache_policies": {
      "get": {
        "summary": "list cache policies",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CachePolicyEntry"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create cache policy",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CachePolicy"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CachePolicyEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/cache_policies/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "get cache policy",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CachePolicyEntry"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "update cache policy",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CachePolicy"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CachePolicyEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete cache policy",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/observability_exporters": {
      "get": {
        "summary": "list observability exporters",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ObservabilityExporterEntry"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create observability exporter",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ObservabilityExporter"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ObservabilityExporterEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/observability_exporters/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "get observability exporter",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ObservabilityExporterEntry"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "update observability exporter",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ObservabilityExporter"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ObservabilityExporterEntry"
                }
              }
            }
          },
          "400": {
            "description": "Schema validation failed or the JSON body is malformed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              },
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "409": {
            "description": "Duplicate name",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "415": {
            "description": "Missing or unsupported JSON content type",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete observability exporter",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/admin/v1/health": {
      "get": {
        "summary": "per-Model upstream health",
        "description": "Returns each Model's health level: 0=Healthy, 1=Degraded (4-7 consecutive upstream failures), 2=Down (8+).",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HealthResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid admin key",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "500": {
            "description": "Configuration store operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          }
        }
      }
    },
    "/playground/chat/completions": {
      "post": {
        "summary": "in-process forward to the proxy router",
        "description": "Forwards a chat completion through the proxy in-process — no extra network hop, but the request is fully audited as if it had arrived on the proxy listener. Auth is a **proxy** ApiKey (`Authorization: Bearer sk-aisix-...`), not an admin key — the proxy middleware validates it inside the forwarded request.",
        "security": [
          {
            "ProxyBearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK. OpenAI-compatible chat completion response.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid proxy API key.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true
                }
              }
            }
          },
          "422": {
            "description": "Proxy validation or guardrail error.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true
                }
              }
            }
          },
          "501": {
            "description": "Proxy router is not wired into this admin router.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AdminError"
                }
              }
            }
          },
          "502": {
            "description": "Upstream proxy error.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true
                }
              }
            }
          },
          "503": {
            "description": "Proxy route unavailable or all routing targets filtered.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": true
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "AdminBearer": {
        "type": "http",
        "scheme": "bearer",
        "description": "Admin key from `config.admin.admin_keys`. Required for every `/admin/v1/*` route."
      },
      "ProxyBearer": {
        "type": "http",
        "scheme": "bearer",
        "description": "Proxy ApiKey (`sk-aisix-...`) — only used by `/playground/chat/completions`."
      }
    },
    "schemas": {
      "ModelEntry": {
        "type": "object",
        "required": [
          "id",
          "value",
          "revision"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "value": {
            "$ref": "#/components/schemas/Model"
          },
          "revision": {
            "type": "integer"
          }
        }
      },
      "ModelStatusView": {
        "type": "object",
        "required": [
          "id",
          "display_name",
          "kind",
          "status"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Resolved model id. Direct-model runtime status is keyed by this id."
          },
          "display_name": {
            "type": "string"
          },
          "kind": {
            "$ref": "#/components/schemas/ModelKind"
          },
          "status": {
            "$ref": "#/components/schemas/RuntimeStatus"
          },
          "cooldown_until": {
            "$ref": "#/components/schemas/SystemTime"
          },
          "last_checked_at": {
            "$ref": "#/components/schemas/SystemTime"
          },
          "last_check_status": {
            "type": "integer",
            "minimum": 100,
            "maximum": 599
          },
          "status_reason": {
            "type": "string",
            "description": "Machine-readable explanation such as `retryable_failure`, `background_check_failed`, or `ignored_transient_error`."
          }
        },
        "description": "Per-model runtime routing status. Routing rows always return `kind=routing` and `status=not_applicable`."
      },
      "ModelKind": {
        "type": "string",
        "enum": [
          "direct",
          "routing"
        ]
      },
      "RuntimeStatus": {
        "type": "string",
        "enum": [
          "healthy",
          "unhealthy",
          "cooldown",
          "not_applicable"
        ]
      },
      "SystemTime": {
        "type": "object",
        "required": [
          "secs_since_epoch",
          "nanos_since_epoch"
        ],
        "properties": {
          "secs_since_epoch": {
            "type": "integer",
            "minimum": 0
          },
          "nanos_since_epoch": {
            "type": "integer",
            "minimum": 0,
            "maximum": 999999999
          }
        }
      },
      "ApiKeyEntry": {
        "type": "object",
        "required": [
          "id",
          "value",
          "revision"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "value": {
            "$ref": "#/components/schemas/PublicApiKey"
          },
          "revision": {
            "type": "integer"
          }
        }
      },
      "AdminError": {
        "type": "object",
        "required": [
          "error_msg"
        ],
        "properties": {
          "error_msg": {
            "type": "string"
          }
        }
      },
      "PublicApiKey": {
        "type": "object",
        "required": [
          "key_hash",
          "allowed_models"
        ],
        "properties": {
          "key_hash": {
            "type": "string",
            "description": "SHA-256 hash of the caller-facing plaintext key."
          },
          "allowed_models": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "rate_limit": {
            "$ref": "#/components/schemas/RateLimit"
          }
        },
        "additionalProperties": false
      },
      "PublicApiKeyEntry": {
        "type": "object",
        "required": [
          "id",
          "value",
          "revision"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "value": {
            "$ref": "#/components/schemas/PublicApiKey"
          },
          "revision": {
            "type": "integer"
          }
        }
      },
      "ApiKeyRotateResponse": {
        "type": "object",
        "required": [
          "entry",
          "plaintext"
        ],
        "properties": {
          "entry": {
            "$ref": "#/components/schemas/PublicApiKeyEntry"
          },
          "plaintext": {
            "type": "string",
            "example": "sk-abcd1234ef567890"
          }
        }
      },
      "ProviderKeyEntry": {
        "type": "object",
        "required": [
          "id",
          "value",
          "revision"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "value": {
            "$ref": "#/components/schemas/ProviderKey"
          },
          "revision": {
            "type": "integer"
          }
        }
      },
      "GuardrailEntry": {
        "type": "object",
        "required": [
          "id",
          "value",
          "revision"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "value": {
            "$ref": "#/components/schemas/Guardrail"
          },
          "revision": {
            "type": "integer"
          }
        }
      },
      "CachePolicyEntry": {
        "type": "object",
        "required": [
          "id",
          "value",
          "revision"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "value": {
            "$ref": "#/components/schemas/CachePolicy"
          },
          "revision": {
            "type": "integer"
          }
        }
      },
      "ObservabilityExporterEntry": {
        "type": "object",
        "required": [
          "id",
          "value",
          "revision"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "value": {
            "$ref": "#/components/schemas/ObservabilityExporter"
          },
          "revision": {
            "type": "integer"
          }
        }
      },
      "DeleteResponse": {
        "type": "object",
        "required": [
          "deleted",
          "id"
        ],
        "properties": {
          "deleted": {
            "type": "boolean",
            "enum": [
              true
            ]
          },
          "id": {
            "type": "string"
          }
        }
      },
      "ModelHealth": {
        "type": "object",
        "required": [
          "id",
          "name",
          "health"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "health": {
            "type": "integer",
            "minimum": 0,
            "maximum": 2,
            "description": "0 healthy, 1 degraded, 2 down."
          }
        }
      },
      "ConfigStatus": {
        "type": "object",
        "required": [
          "snapshot_revision",
          "snapshot_age_seconds"
        ],
        "properties": {
          "snapshot_revision": {
            "type": "integer"
          },
          "snapshot_age_seconds": {
            "type": [
              "integer",
              "null"
            ],
            "minimum": 0
          }
        }
      },
      "HealthResponse": {
        "type": "object",
        "required": [
          "status",
          "models"
        ],
        "properties": {
          "status": {
            "type": "string",
            "enum": [
              "ok"
            ]
          },
          "models": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ModelHealth"
            }
          },
          "config": {
            "$ref": "#/components/schemas/ConfigStatus"
          }
        }
      },
      "ApiKeyRequest": {
        "type": "object",
        "required": [
          "key_hash",
          "allowed_models"
        ],
        "properties": {
          "key_hash": {
            "type": "string",
            "description": "SHA-256 hash of the caller-facing plaintext key."
          },
          "allowed_models": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "rate_limit": {
            "$ref": "#/components/schemas/RateLimit"
          }
        },
        "additionalProperties": false,
        "description": "Standalone Admin API request body for creating or updating a caller API key. Cloud-projected ownership fields are not accepted by the self-hosted Admin API."
      }
    }
  },
  "security": [
    {
      "AdminBearer": []
    }
  ]
}"##;

const SCALAR_HTML: &str = r#"<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>aisix admin OpenAPI</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <script
      id="api-reference"
      data-url="/admin/openapi.json"
      type="application/javascript"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>"#;

/// Resource schemas embedded at compile time from
/// `<workspace-root>/schemas/resources/*.schema.json`. The build will
/// fail if a file is missing — that is intentional, the canonical
/// schemas must exist before this crate compiles.
const RESOURCE_SCHEMAS: &[(&str, &str)] = &[
    (
        "Model",
        include_str!("../../../schemas/resources/model.schema.json"),
    ),
    (
        "ApiKey",
        include_str!("../../../schemas/resources/api_key.schema.json"),
    ),
    (
        "ProviderKey",
        include_str!("../../../schemas/resources/provider_key.schema.json"),
    ),
    (
        "Guardrail",
        include_str!("../../../schemas/resources/guardrail.schema.json"),
    ),
    (
        "CachePolicy",
        include_str!("../../../schemas/resources/cache_policy.schema.json"),
    ),
    (
        "ObservabilityExporter",
        include_str!("../../../schemas/resources/observability_exporter.schema.json"),
    ),
    (
        "RateLimit",
        include_str!("../../../schemas/resources/rate_limit.schema.json"),
    ),
    (
        "Routing",
        include_str!("../../../schemas/resources/routing.schema.json"),
    ),
];

/// Build the merged OpenAPI document on first call and cache for the
/// process lifetime. The result is what `GET /admin/openapi.json`
/// serves; the constants above hold only the input fragments.
///
/// `pub(crate)` so [`crate::build_router`] can pre-warm it at startup
/// — `OnceLock::get_or_init` panics here would otherwise surface only
/// on the first `/admin/openapi.json` request, well after boot, which
/// is a worse ops failure mode than crashing immediately.
pub(crate) fn merged_openapi() -> &'static str {
    static CELL: OnceLock<String> = OnceLock::new();
    CELL.get_or_init(|| {
        let mut doc: Value =
            serde_json::from_str(OPENAPI_JSON_BASE).expect("OPENAPI_JSON_BASE must parse as JSON");

        for (name, raw) in RESOURCE_SCHEMAS {
            let mut schema: Value = serde_json::from_str(raw)
                .unwrap_or_else(|e| panic!("schema {name} must parse: {e}"));

            // Hoist `definitions/*` to top-level `components.schemas/*`.
            // The first definition wins — `Routing` appears both as a
            // standalone resource and nested in `Model`; they are
            // produced from the same Rust type so the content is
            // identical, but we still guard against double-write.
            if let Some(obj) = schema.as_object_mut() {
                if let Some(Value::Object(defs)) = obj.remove("definitions") {
                    for (def_name, def_value) in defs {
                        let target = &mut doc["components"]["schemas"][&def_name];
                        if target.is_null() {
                            *target = def_value;
                        }
                    }
                }
            }

            // Strip JSON Schema meta-fields that do not belong on an
            // inline OpenAPI 3.1 component schema.
            if let Some(obj) = schema.as_object_mut() {
                obj.remove("$schema");
                obj.remove("title");
            }

            doc["components"]["schemas"][*name] = schema;
        }

        // Rewrite `$ref: #/definitions/X` → `$ref: #/components/schemas/X`
        // everywhere in the merged doc (covers both the top-level
        // resource schemas and the already-hoisted nested ones).
        rewrite_definitions_refs(&mut doc);

        serde_json::to_string(&doc).expect("merged OpenAPI must serialise")
    })
}

/// Walk a JSON value, rewriting `{"$ref": "#/definitions/X"}` strings
/// to `{"$ref": "#/components/schemas/X"}`. `schemars` 0.8 emits the
/// JSON Schema draft-07 form; OpenAPI 3.1 requires the
/// `components/schemas` form for in-document references.
fn rewrite_definitions_refs(v: &mut Value) {
    match v {
        Value::Object(map) => {
            for (k, val) in map.iter_mut() {
                if k == "$ref" {
                    if let Value::String(s) = val {
                        if let Some(suffix) = s.strip_prefix("#/definitions/") {
                            *val = Value::String(format!("#/components/schemas/{suffix}"));
                        }
                    }
                } else {
                    rewrite_definitions_refs(val);
                }
            }
        }
        Value::Array(items) => {
            for item in items {
                rewrite_definitions_refs(item);
            }
        }
        _ => {}
    }
}

pub async fn openapi_json() -> Response {
    (
        [(header::CONTENT_TYPE, "application/json")],
        merged_openapi(),
    )
        .into_response()
}

pub async fn openapi_scalar() -> Html<&'static str> {
    Html(SCALAR_HTML)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn openapi_json_is_well_formed_and_documents_admin_paths() {
        let resp = openapi_json().await;
        assert_eq!(resp.status(), 200);
        // Validate by parsing — guards against typos in the literal block.
        let parsed: serde_json::Value =
            serde_json::from_str(merged_openapi()).expect("merged_openapi must parse");
        // Every route mounted in build_router should be documented.
        for path in [
            "/livez",
            "/admin/openapi.json",
            "/admin/openapi-scalar",
            "/admin/v1/models",
            "/admin/v1/models/{id}",
            "/admin/v1/models/status",
            "/admin/v1/apikeys",
            "/admin/v1/apikeys/{id}",
            "/admin/v1/apikeys/{id}/rotate",
            "/admin/v1/provider_keys",
            "/admin/v1/provider_keys/{id}",
            "/admin/v1/guardrails",
            "/admin/v1/guardrails/{id}",
            "/admin/v1/cache_policies",
            "/admin/v1/cache_policies/{id}",
            "/admin/v1/observability_exporters",
            "/admin/v1/observability_exporters/{id}",
            "/admin/v1/health",
            "/playground/chat/completions",
        ] {
            assert!(
                parsed["paths"][path].is_object(),
                "merged OpenAPI missing path {path}"
            );
        }
        // Reusable schemas referenced from the path bodies.
        for schema in [
            "Model",
            "ModelEntry",
            "BackgroundModelCheck",
            "ModelStatusView",
            "ModelKind",
            "RuntimeStatus",
            "SystemTime",
            "ApiKey",
            "ApiKeyRequest",
            "ApiKeyEntry",
            "PublicApiKey",
            "PublicApiKeyEntry",
            "ApiKeyRotateResponse",
            "ProviderKey",
            "ProviderKeyEntry",
            "Guardrail",
            "GuardrailEntry",
            "CachePolicy",
            "CachePolicyEntry",
            "ObservabilityExporter",
            "ObservabilityExporterEntry",
            "RateLimit",
            "Routing",
            "ModelCost",
            "DeleteResponse",
            "ModelHealth",
            "ConfigStatus",
            "HealthResponse",
            "AdminError",
        ] {
            assert!(
                parsed["components"]["schemas"][schema].is_object(),
                "merged OpenAPI missing schema {schema}"
            );
        }
    }

    #[tokio::test]
    async fn openapi_documents_exact_admin_path_set() {
        use std::collections::BTreeSet;

        let parsed: serde_json::Value =
            serde_json::from_str(merged_openapi()).expect("merged_openapi must parse");
        let actual: BTreeSet<_> = parsed["paths"]
            .as_object()
            .expect("paths must be an object")
            .keys()
            .map(String::as_str)
            .collect();
        let expected = BTreeSet::from([
            "/livez",
            "/admin/openapi.json",
            "/admin/openapi-scalar",
            "/admin/v1/models",
            "/admin/v1/models/{id}",
            "/admin/v1/models/status",
            "/admin/v1/apikeys",
            "/admin/v1/apikeys/{id}",
            "/admin/v1/apikeys/{id}/rotate",
            "/admin/v1/provider_keys",
            "/admin/v1/provider_keys/{id}",
            "/admin/v1/guardrails",
            "/admin/v1/guardrails/{id}",
            "/admin/v1/cache_policies",
            "/admin/v1/cache_policies/{id}",
            "/admin/v1/observability_exporters",
            "/admin/v1/observability_exporters/{id}",
            "/admin/v1/health",
            "/playground/chat/completions",
        ]);

        assert_eq!(
            actual, expected,
            "OpenAPI paths must match the admin router exactly; metrics live on the dedicated metrics listener"
        );
    }

    #[tokio::test]
    async fn openapi_uses_standalone_apikey_request_schema() {
        let parsed: serde_json::Value =
            serde_json::from_str(merged_openapi()).expect("merged_openapi must parse");
        for (path, method) in [
            ("/admin/v1/apikeys", "post"),
            ("/admin/v1/apikeys/{id}", "put"),
        ] {
            assert_eq!(
                parsed["paths"][path][method]["requestBody"]["content"]["application/json"]
                    ["schema"]["$ref"],
                "#/components/schemas/ApiKeyRequest",
                "{method} {path} should document the standalone Admin API request body"
            );
        }

        let request = &parsed["components"]["schemas"]["ApiKeyRequest"];
        assert_eq!(request["required"][0], "key_hash");
        assert_eq!(request["required"][1], "allowed_models");
        assert!(request["properties"].get("team_id").is_none());
        assert!(request["properties"].get("user_id").is_none());
    }

    #[tokio::test]
    async fn openapi_documents_response_schemas_for_all_statuses() {
        let parsed: serde_json::Value =
            serde_json::from_str(merged_openapi()).expect("merged_openapi must parse");
        let paths = parsed["paths"]
            .as_object()
            .expect("paths must be an object");

        for (path, path_item) in paths {
            let path_item = path_item.as_object().expect("path item must be an object");
            for (method, operation) in path_item {
                if method == "parameters" {
                    continue;
                }
                let responses = operation["responses"]
                    .as_object()
                    .unwrap_or_else(|| panic!("{method} {path} must define responses"));
                for (status, response) in responses {
                    let Some(content) = response["content"].as_object() else {
                        panic!("{method} {path} response {status} missing content schema");
                    };
                    let has_schema = content.values().any(|media| media["schema"].is_object());
                    assert!(
                        has_schema,
                        "{method} {path} response {status} missing media schema"
                    );
                }
            }
        }
    }

    #[tokio::test]
    async fn openapi_documents_admin_auth_and_error_envelope() {
        let parsed: serde_json::Value =
            serde_json::from_str(merged_openapi()).expect("merged_openapi must parse");
        let paths = parsed["paths"]
            .as_object()
            .expect("paths must be an object");

        for (path, path_item) in paths {
            if !path.starts_with("/admin/v1/") {
                continue;
            }
            let path_item = path_item.as_object().expect("path item must be an object");
            for (method, operation) in path_item {
                if method == "parameters" {
                    continue;
                }
                let responses = operation["responses"]
                    .as_object()
                    .unwrap_or_else(|| panic!("{method} {path} must define responses"));
                let unauthorized = responses
                    .get("401")
                    .unwrap_or_else(|| panic!("{method} {path} missing 401 response"));
                assert_eq!(
                    unauthorized["content"]["application/json"]["schema"]["$ref"],
                    "#/components/schemas/AdminError",
                    "{method} {path} 401 should use AdminError"
                );
            }
        }
    }

    #[tokio::test]
    async fn openapi_unauthenticated_routes_carry_empty_security() {
        // /livez and the openapi self-references are public (mirrors the
        // design note in build_router). The spec must mark them with
        // security: [] so Scalar's "Try it" doesn't prompt for an admin
        // key on those routes.
        let parsed: serde_json::Value =
            serde_json::from_str(merged_openapi()).expect("merged_openapi must parse");
        for path in ["/livez", "/admin/openapi.json", "/admin/openapi-scalar"] {
            let security = &parsed["paths"][path]["get"]["security"];
            assert!(
                security.is_array() && security.as_array().unwrap().is_empty(),
                "{path} should declare security: [] but got {security:?}"
            );
        }
    }

    #[tokio::test]
    async fn openapi_livez_documents_plain_ok() {
        let parsed: serde_json::Value =
            serde_json::from_str(merged_openapi()).expect("merged_openapi must parse");
        let schema = &parsed["paths"]["/livez"]["get"]["responses"]["200"]["content"]["text/plain"]
            ["schema"];

        assert_eq!(schema["type"], "string");
        assert!(schema.get("enum").is_none());
        assert_eq!(
            parsed["paths"]["/livez"]["get"]["parameters"][0]["name"],
            "verbose"
        );
        assert!(parsed["paths"]["/livez"]["get"]["responses"]["500"].is_object());
    }

    #[tokio::test]
    async fn scalar_html_loads_the_spec_url() {
        let html = openapi_scalar().await;
        let body = html.0;
        assert!(body.contains("/admin/openapi.json"));
        assert!(body.contains("scalar"));
    }
}
